import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {getCaptchaConfig,verifyContact} from '../server/contact-worker.mjs';
const site='https://irisha.example';
const env={RECAPTCHA_SITE_KEY:'configured-key',RECAPTCHA_SECRET_KEY:'configured-secret',RECAPTCHA_ALLOWED_HOSTNAMES:'irisha.example',CONTACT_WHATSAPP:'919876543210'};
const make=(body={token:'valid-token',company_website:''},options={})=>new Request(site+'/api/contact',{method:'POST',headers:{'Content-Type':'application/json',Origin:site,...options.headers},body:typeof body==='string'?body:JSON.stringify(body),...options.init});
assert.equal(getCaptchaConfig(new Request(site+'/api/captcha-config'),{}).status,503);
assert.equal((await verifyContact(make(),{})).status,503);
assert.equal((await getCaptchaConfig(new Request(site+'/api/captcha-config'),{...env,RECAPTCHA_SITE_KEY:'6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'})).status,503);
const publicConfig=await getCaptchaConfig(new Request(site+'/api/captcha-config'),env).text();
assert(publicConfig.includes('configured-key'));
assert(!publicConfig.includes(env.RECAPTCHA_SECRET_KEY)&&!publicConfig.includes(env.CONTACT_WHATSAPP));
assert.equal((await verifyContact(new Request(site+'/api/contact'),env)).status,405);
assert.equal((await verifyContact(make(undefined,{headers:{Origin:'https://attacker.example'}}),env)).status,403);
assert.equal((await verifyContact(make(undefined,{headers:{'Sec-Fetch-Site':'cross-site'}}),env)).status,403);
assert.equal((await verifyContact(make(undefined,{headers:{'Content-Type':'text/plain'}}),env)).status,415);
assert.equal((await verifyContact(make({token:'',company_website:''}),env)).status,400);
assert.equal((await verifyContact(make({token:'valid',company_website:'spam.example'}),env)).status,400);
assert.equal((await verifyContact(make('x'.repeat(13000)),env)).status,400);
const savedFetch=globalThis.fetch;
let calls=0;
try{
 globalThis.fetch=async(url,init)=>{
  calls++;assert.equal(url,'https://www.google.com/recaptcha/api/siteverify');
  const body=new URLSearchParams(init.body);
  assert.equal(body.get('secret'),env.RECAPTCHA_SECRET_KEY);
  assert.equal(body.get('response'),'valid-token');
  return Response.json(calls===1?{success:true,hostname:'irisha.example'}:{success:false,'error-codes':['timeout-or-duplicate']});
 };
 const success=await verifyContact(make(),env);assert.equal(success.status,200);
 assert.equal((await success.json()).whatsappUrl,'https://wa.me/'+env.CONTACT_WHATSAPP);
 assert(success.headers.get('cache-control').includes('no-store'));
 const replay=await verifyContact(make(),env);assert.equal(replay.status,403);assert(!(await replay.text()).includes(env.CONTACT_WHATSAPP));
 globalThis.fetch=async()=>Response.json({success:true,hostname:'attacker.example'});
 assert.equal((await verifyContact(make(),env)).status,403);
 globalThis.fetch=async()=>Response.json({success:false});
 assert.equal((await verifyContact(make(),env)).status,403);
 globalThis.fetch=async()=>{throw Error('provider timeout');};
 assert.equal((await verifyContact(make(),env)).status,503);
}finally{globalThis.fetch=savedFetch;}
const app=await readFile('dist/app.js','utf8');
assert(!app.includes('settings.whatsapp')&&!app.includes('phone_display'),'Client contact bypass');
const html=await readFile('dist/index.html','utf8');
const dialogs=[...html.matchAll(/<dialog\b[\s\S]*?<\/dialog>/g)].map(m=>m[0]);
assert(dialogs.every(dialog=>!dialog.includes('id="captcha-widget"')),'Challenge must be outside native modal dialogs');
const worker=await import('../dist/server/index.js');
const homepage=await worker.default.fetch(new Request(site+'/'),env);
assert.equal(homepage.status,200);assert((await homepage.text()).includes('id="contact-verification"'));
assert.equal(homepage.headers.get('x-frame-options'),null,'Public pages must allow the ChatGPT embed');
assert.equal(homepage.headers.get('content-security-policy').split('frame-ancestors ')[1],"'self' https://chatgpt.com",'Allow only the site itself and the trusted ChatGPT parent');
const unconfiguredHomepage=await worker.default.fetch(new Request(site+'/'),{});
assert.equal(unconfiguredHomepage.status,200,'Missing CAPTCHA keys must not prevent the website from loading');
const admin=await worker.default.fetch(new Request(site+'/admin/'),env);
assert.equal(admin.headers.get('x-frame-options'),'SAMEORIGIN');
assert.equal(admin.headers.get('content-security-policy').split('frame-ancestors ')[1],"'self'",'Keep CMS embedding restricted');
const asset=await worker.default.fetch(new Request(site+'/assets/varanasi-hero.webp'),env);
assert.equal(asset.headers.get('content-type'),'image/webp');assert((await asset.arrayBuffer()).byteLength>10000);
assert.equal((await worker.default.fetch(new Request(site+'/does-not-exist'),env)).status,404);
assert.equal((await worker.default.fetch(new Request(site+'/api/captcha-config'),{})).status,503);
console.log('PASS: missing keys, test keys, request bounds, origin, honeypot, invalid/expired/replayed tokens, hostname, provider failure, contact privacy, Worker assets and trusted preview embedding.');
